POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Inception",
    "synopsis": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
    "year": 2010,
    "rating": 8.8
}

###

GET http://localhost:3000/movies HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/movies/1 HTTP/1.1
content-type: application/json

